#!/usr/bin/env python3
"""Manage the pdf-studio site library under $XDG_DATA_HOME/pdf-studio.

The library is a single, persistent deploy root that accumulates books as
subpaths, so one Cloudflare Pages project (and one Access policy) serves the
whole collection. This script does only local filesystem + JSON work — no
network, no wrangler. The skills run wrangler separately.

Layout:
  <root>/                       $XDG_DATA_HOME/pdf-studio (or ~/.local/share/...)
  ├── library.json              metadata (NOT deployed): project, books, access
  └── public/                   the deploy root (uploaded whole by wrangler)
      ├── index.html            library index, rebuilt from library.json
      ├── assets/style.css      shared design system (copied from generate-site)
      └── <slug>/               one book's authored site (copied from a work dir)

Subcommands:
  path                          print the library root
  status                        print library.json (or a not-initialized notice)
  project                       print the recorded Cloudflare Pages project name
  public                        print the deploy root (<root>/public)
  init --project NAME [--title T] [--force]
                                create the library and an empty index
  add --slug S --title T [--desc D] --from DIR
                                copy DIR into public/<S>/, record it, rebuild index
"""

import argparse
import datetime
import html
import json
import os
import re
import shutil
import sys
from pathlib import Path

SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def root():
    base = os.environ.get("XDG_DATA_HOME") or os.path.join(
        os.path.expanduser("~"), ".local", "share"
    )
    return Path(base) / "pdf-studio"


def meta_path():
    return root() / "library.json"


def public_dir():
    return root() / "public"


def load_meta():
    p = meta_path()
    if not p.exists():
        sys.exit(
            "error: library not initialized (%s missing). Run the initialize-site "
            "skill first." % p
        )
    return json.loads(p.read_text(encoding="utf-8"))


def save_meta(meta):
    meta_path().write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def style_css_source():
    # This script's own bundled copy of the shared design system:
    # pdf-studio-site-base/scripts/library.py -> pdf-studio-site-base/assets/style.css
    return Path(__file__).resolve().parents[1] / "assets" / "style.css"


def today():
    return datetime.date.today().isoformat()


# ---------------------------------------------------------------- index render

INDEX = """\
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="pdf-studio">
<title>{title}</title>
<link rel="stylesheet" href="assets/style.css">
</head>
<body>
<main>
  <div class="hero">
    <p class="kicker">蔵書</p>
    <h1>{title}</h1>
    <p class="lede">{lede}</p>
    <div class="meta"><span class="chip">{count}冊</span></div>
  </div>
{body}
</main>
<footer>Generated by pdf-studio</footer>
</body>
</html>
"""


def render_index(meta):
    books = meta.get("books", [])
    title = html.escape(meta.get("title") or "Reading Library")
    if books:
        lede = "これまでに読んだ本のガイド。各カードから本文と音声ガイドを開けます。"
        cards = ['<ol class="cards">']
        for b in books:
            slug = html.escape(b["slug"])
            bt = html.escape(b.get("title") or b["slug"])
            desc = html.escape(b.get("desc") or "")
            chip = '<span class="chip">🔊 音声ガイドあり</span>' if b.get("audio") else ""
            cards.append(
                '  <li><a href="%s/"><span class="t">%s</span>'
                '<span class="s">%s</span>%s</a></li>' % (slug, bt, desc, chip)
            )
        cards.append("</ol>")
        body = "\n".join(cards)
    else:
        lede = "まだ本がありません。deploy-site スキルで本を追加してください。"
        body = "  <p>（蔵書は空です）</p>"
    return INDEX.format(
        title=title, lede=html.escape(lede), count=len(books), body=body
    )


def write_public_scaffold(meta):
    pub = public_dir()
    (pub / "assets").mkdir(parents=True, exist_ok=True)
    src = style_css_source()
    if src.exists():
        shutil.copy2(src, pub / "assets" / "style.css")
    else:
        # Fallback: minimal readable stylesheet if the sibling asset moved.
        (pub / "assets" / "style.css").write_text(
            "body{font-family:sans-serif;max-width:45rem;margin:0 auto;padding:1rem;}",
            encoding="utf-8",
        )
    (pub / "index.html").write_text(render_index(meta), encoding="utf-8")


# ---------------------------------------------------------------- commands


def cmd_init(args):
    if not SLUG_RE.match(args.project):
        sys.exit("error: project name must be lowercase a-z0-9- (got %r)" % args.project)
    mp = meta_path()
    if mp.exists() and not args.force:
        existing = json.loads(mp.read_text(encoding="utf-8"))
        sys.exit(
            "error: library already initialized (project %r at %s). Use --force to "
            "reinitialize." % (existing.get("project"), root())
        )
    root().mkdir(parents=True, exist_ok=True)
    meta = {
        "project": args.project,
        "title": args.title or "Reading Library",
        "created": today(),
        "access": False,
        "books": [],
    }
    save_meta(meta)
    write_public_scaffold(meta)
    print("library root: %s" % root())
    print("deploy root:  %s" % public_dir())
    print("project:      %s" % args.project)


def cmd_add(args):
    if not SLUG_RE.match(args.slug):
        sys.exit("error: slug must be lowercase a-z0-9- (got %r)" % args.slug)
    meta = load_meta()
    src = Path(args.src).resolve()
    if not (src / "index.html").is_file():
        sys.exit("error: --from %s has no index.html (point it at a generate-site site/ dir)" % src)

    dest = public_dir() / args.slug
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    has_audio = (dest / "audio").is_dir() and any((dest / "audio").iterdir())

    books = [b for b in meta.get("books", []) if b["slug"] != args.slug]
    replaced = len(books) != len(meta.get("books", []))
    books.append(
        {
            "slug": args.slug,
            "title": args.title,
            "desc": args.desc or "",
            "audio": has_audio,
            "added": today(),
        }
    )
    # Keep a stable order: most-recently-added last.
    meta["books"] = books
    save_meta(meta)
    write_public_scaffold(meta)

    print("%s book %r at public/%s/" % ("updated" if replaced else "added", args.title, args.slug))
    print("url path: /%s/" % args.slug)
    print("deploy root: %s" % public_dir())


def main():
    ap = argparse.ArgumentParser(description="Manage the pdf-studio site library.")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("path")
    sub.add_parser("status")
    sub.add_parser("project")
    sub.add_parser("public")

    pi = sub.add_parser("init")
    pi.add_argument("--project", required=True)
    pi.add_argument("--title")
    pi.add_argument("--force", action="store_true")

    pa = sub.add_parser("add")
    pa.add_argument("--slug", required=True)
    pa.add_argument("--title", required=True)
    pa.add_argument("--desc")
    pa.add_argument("--from", dest="src", required=True)

    args = ap.parse_args()
    if args.cmd == "path":
        print(root())
    elif args.cmd == "public":
        print(public_dir())
    elif args.cmd == "status":
        p = meta_path()
        if not p.exists():
            print("not initialized (%s missing)" % p)
        else:
            print(p.read_text(encoding="utf-8"), end="")
    elif args.cmd == "project":
        print(load_meta().get("project", ""))
    elif args.cmd == "init":
        cmd_init(args)
    elif args.cmd == "add":
        cmd_add(args)


if __name__ == "__main__":
    main()
